<a href="https://colab.research.google.com/github/shivanshthakur0107-pixel/Shivansh-singh/blob/main/data_transform4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Data structure
# Handle Missing values
# Data Transformation
# String Manipulation

In [1]:
import numpy as np
import pandas as pd

In [7]:
# create your own dataset


data={'Student_ID':[101,102,103,104,105,106,107,108,109,110,111,112],
    'Name':['Rahul kumar','Amit sharma','Priya singh','Neha verma','Ravi','ANjali gupta','VIkas singh','Pooja shrama','Karan mehta','Sneha kumari','Arjun singh','Riya verma'],

    'Gender':['Male','Male','Female','Female','Male','Female','Male','Female','Male','Female','Male','Female'],
    'Department':['CSE','CSE','ECE','CSE','ECE','CSE','ME','CSE','ECE','ME','CSE','ECE',],
    'Age':[20,21,np.nan,22,21,20,23,np.nan,22,21,20,22],
    'Attendence':[85,72,np.nan,75,88,65,92,np.nan,76,64,95,81],
    'Marks':[85,72,np.nan,91,68,88,55,np.nan,76,64,95,81],
    'Email':['rahul@gmail.com','amit@gmail.com','priya@gmail.com','neha@gmail.com','None','anjali@gmail.com','vikas@gmail.com','pooja@gmail.com','None','None','None','None']
}
df=pd.DataFrame(data)
display(df)

,Student_ID,Name,Gender,Department,Age,Attendence,Marks,Email
0,101,Rahul kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com
1,102,Amit sharma,Male,CSE,21.0,72.0,72.0,amit@gmail.com
2,103,Priya singh,Female,ECE,NaN,NaN,NaN,priya@gmail.com
3,104,Neha verma,Female,CSE,22.0,75.0,91.0,neha@gmail.com
4,105,Ravi,Male,ECE,21.0,88.0,68.0,None
5,106,ANjali gupta,Female,CSE,20.0,65.0,88.0,anjali@gmail.com
6,107,VIkas singh,Male,ME,23.0,92.0,55.0,vikas@gmail.com
7,108,Pooja shrama,Female,CSE,NaN,NaN,NaN,pooja@gmail.com
8,109,Karan mehta,Male,ECE,22.0,76.0,76.0,None
9,110,Sneha kumari,Female,ME,21.0,64.0,64.0,None
10,111,Arjun singh,Male,CSE,20.0,95.0,95.0,None
11,112,Riya verma,Female,ECE,22.0,81.0,81.0,None

In [8]:
print('Shape:',df.shape)
print('Columns:',df.columns.tolist)
print('Data Types:',df.dtypes)
display(df.head())
display(df.tail())

Shape: (12, 8)
Columns: <bound method IndexOpsMixin.tolist of Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendence',
       'Marks', 'Email'],
      dtype='object')>
Data Types: Student_ID      int64
Name           object
Gender         object
Department     object
Age           float64
Attendence    float64
Marks         float64
Email          object
dtype: object

,Student_ID,Name,Gender,Department,Age,Attendence,Marks,Email
0,101,Rahul kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com
1,102,Amit sharma,Male,CSE,21.0,72.0,72.0,amit@gmail.com
2,103,Priya singh,Female,ECE,NaN,NaN,NaN,priya@gmail.com
3,104,Neha verma,Female,CSE,22.0,75.0,91.0,neha@gmail.com
4,105,Ravi,Male,ECE,21.0,88.0,68.0,None

,Student_ID,Name,Gender,Department,Age,Attendence,Marks,Email
7,108,Pooja shrama,Female,CSE,NaN,NaN,NaN,pooja@gmail.com
8,109,Karan mehta,Male,ECE,22.0,76.0,76.0,None
9,110,Sneha kumari,Female,ME,21.0,64.0,64.0,None
10,111,Arjun singh,Male,CSE,20.0,95.0,95.0,None
11,112,Riya verma,Female,ECE,22.0,81.0,81.0,None

In [11]:
# Detect Missing values
print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Department    0
Age           2
Attendence    2
Marks         2
Email         0
dtype: int64

In [14]:
#Handle the missing values
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Attendence']=df['Attendence'].fillna(df['Attendence'].median())
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df['Email']=df['Email'].fillna('Not Provided')
print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Department    0
Age           0
Attendence    0
Marks         0
Email         0
dtype: int64

In [15]:
#data Transformation
df['Result']=df['Marks'].apply(lambda x:'PAss' if x>=40 else 'Fail')


def assign_grade(marks):
  if marks>=80:return 'A'
  elif marks>=60:return 'B'
  elif marks>=60:return 'C'
  elif marks>=50:return 'D'
  else:return 'F'
df['Grade']=df['Marks'].apply(assign_grade)
display(df)

,Student_ID,Name,Gender,Department,Age,Attendence,Marks,Email,Result,Grade
0,101,Rahul kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com,PAss,A
1,102,Amit sharma,Male,CSE,21.0,72.0,72.0,amit@gmail.com,PAss,B
2,103,Priya singh,Female,ECE,21.2,78.5,77.5,priya@gmail.com,PAss,B
3,104,Neha verma,Female,CSE,22.0,75.0,91.0,neha@gmail.com,PAss,A
4,105,Ravi,Male,ECE,21.0,88.0,68.0,None,PAss,B
5,106,ANjali gupta,Female,CSE,20.0,65.0,88.0,anjali@gmail.com,PAss,A
6,107,VIkas singh,Male,ME,23.0,92.0,55.0,vikas@gmail.com,PAss,D
7,108,Pooja shrama,Female,CSE,21.2,78.5,77.5,pooja@gmail.com,PAss,B
8,109,Karan mehta,Male,ECE,22.0,76.0,76.0,None,PAss,B
9,110,Sneha kumari,Female,ME,21.0,64.0,64.0,None,PAss,B
10,111,Arjun singh,Male,CSE,20.0,95.0,95.0,None,PAss,A
11,112,Riya verma,Female,ECE,22.0,81.0,81.0,None,PAss,A